### ISSUE TITLE
Slow download speeds for ct when building deployment base image

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/metal-dockerfiles#14]
I was trying to build deployment base image locally, since loading it from registry is very slow for some reason. I found out that part when it tries to load `container-linux-config-transpiler` with curl is very slow:
![ct](https://user-images.githubusercontent.com/3637857/101671819-4f2e5600-3a55-11eb-9071-bfb3992f05a8.png)

As you see, expected time was 2 hours and counting.  Which is just too much. I solved it by building `ct` executable from source. So, if anyone else encountered this problem of slow download speeds of `ct` before, probably we should look into solving it properly.

cc @mwindower @Gerrit91

**Comment by Gerrit91** [comment]
Downloading artifacts from Github (Packages, i.e. release assets or GHCR images) can be rather slow in the evening when their AWS S3 backend is crowded. I am not sure how we could resolve this?

**Comment by GrigoriyMikhalkin** [comment]
One solution could be using multi stage build, where some dependencies are building from source in first stage. But that's, messy solution.
