### ISSUE TITLE
Upgrade Helm

### ISSUE THREAD

**Issue by ulrichSchreiner** [metal-stack/metal-dockerfiles#5]
when installing `cert-manager` with the `installCRDs=true` option you need at least helm >3.3.1

https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/#helm

> Helm users who use installCRDs=true MUST upgrade to Helm v3.3.1 or later before upgrading.

this fix is really needed, otherwise the helm deployment of cert-manager hangs.

so it would be great to update helm to the latest 3.x.y version

**Comment by Gerrit91** [comment]
Closed through #6.
